app_runner_service_name = "iv-smile-service"
aws_region = "us-east-1"
# Agrega aquí otras variables necesarias para tu infraestructura, por ejemplo:
# ecr_repo_name = "iv-smile-app"
# dynamodb_table_name = "dev-raw-prices"
# raw_table_name = "dev-raw-prices"
# iv_table_name = "dev-implied-vols"
# lambda_role_name = "dev-lambda-exec"
# scraper_lambda_name = "dev-scraper-lambda"
# iv_lambda_name = "dev-iv-lambda" 