# Variables para Terraform
 ecr_repo_name            = "iv-smile-app"
 app_runner_service_name  = "iv-smile-service"
 s3_bucket_name           = "iv-smile-data"
 dynamodb_table_name      = "iv-smile-metadata"
 raw_table_name           = "dev-raw-prices"
 iv_table_name            = "dev-implied-vols"
 lambda_role_name         = "dev-lambda-exec"
 scraper_lambda_name      = "dev-scraper-lambda"
 iv_lambda_name           = "dev-iv-lambda"