FROM public.ecr.aws/lambda/python:3.9
WORKDIR /var/task

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api_embudo_lambda.py .

CMD ["api_embudo_lambda.lambda_handler"] 