FROM public.ecr.aws/lambda/python:3.9
WORKDIR /var/task

COPY iv_smile_project/lambda/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY iv_smile_project/lambda/iv_lambda.py .
# COPY scraper/ ./scraper/

CMD ["iv_lambda.lambda_handler"] 